consultant:
    resource: "@ConsultantBundle/Controller/"
    type:     annotation
    prefix:   /consultant

users:
    resource: "@UsersBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@CalendarBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
